app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path: /login
    defaults:
        _controller: AppBundle:User:login
        
login_check:
    path: /login_check

logout:
    path: /logout
