# app/config/security.yml
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: AppBundle:User, property: userName }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: true
            form_login:
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout
                target: homepage
            guard:
                authenticators:
                    - AppBundle\Security\LoginAuthenticator